### ISSUE TITLE
FR: Collapse all branches

### ISSUE THREAD

**Issue by aspiers** [markmap/markmap-vscode#19]
Thanks for this great extension.  When opening a large mind-map, it is hard to navigate because it is so huge.  It would be really helpful if there was a way to collapse all branches in one go, and even better if this was optionally done when first rendering the map.

**Comment by CleoQc** [comment]
Yes please! I have a pretty large mindmap too, and I'm trying to figure out if this has been implemented?

**Comment by harrybou** [comment]
Absolutely essential, I reckon.  Would be nice to be able to specify the level to open to.  Also, if root level could be level 0 rather than at the top of level 1.

**Comment by harrybou** [comment]
One other thing. It would also be nice if when you open a level, only that level opens, not all higher levels For example if you are on level two, and click on a 'dot' only level three opens, not level three to 'x'.

**Comment by jawspeak** [comment]
Curious the usability how folks would want this, because I'm interested also in this. 

1. One idea is to try and listen to `command-shift-p` commands to fold / unfold similar to how you can in code, and keep the markmind map in sync with the code folding level. OR, have another set of shortcut commands for just the mindmap:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/44742/203574661-db4757e0-d9b5-470f-b1d0-0be08c6f5bd0.png">

<img width="489" alt="image" src="https://user-images.githubusercontent.com/44742/203574762-ef31c5ee-9884-4f25-a6d6-1e71b747dd59.png">


2. Another idea is to have buttons in the markmap control in the bottom right of the window 
<img width="249" alt="image" src="https://user-images.githubusercontent.com/44742/203575077-38e35c1e-c763-48fe-90a1-bc4737a33ce6.png">

3. Is there another user experience folks would be interested in? 

I'm interested in trying a PR of this, just seeking some feedback @markmap the best UX (and also pointers for implementation). :-)

**Comment by gera2ld** [comment]
![image](https://user-images.githubusercontent.com/3139113/203645908-44f9fd94-65d4-455a-aaeb-35e62f41106a.png)

This button is used to fold/unfold the next node and its children recursively. Maybe it was a bad UX 😂

**Comment by jawspeak** [comment]
Ohhh interesting, thank you so much. I don't think I figured out how to use that when I tried (macOS Chrome) in https://markmap.js.org/repl Clicking that nothing happened. I'm not sure where the state of the current node is indicated to recursively toggle from.

**Comment by jawspeak** [comment]
I implemented a keyboard level version of this in another library today which possibly we could share inspiration from / etc. https://github.com/lynchjames/obsidian-mind-map/pull/103
